Get Windows Perl version by looking at what's available in berrybrew
The most recent berrybrew release removed 5.30.0 as an available Perl. The
author will add it back, but it's probably best to just pick the most recent
version.

diff --git a/templates/windows.yml b/templates/windows.yml
--- a/templates/windows.yml
+++ b/templates/windows.yml
@@ -1,7 +1,7 @@
 parameters:
   cache_key: 'cache'
-  name: ''
-  perl: ''
+  name: 'stable'
+  perl: 'stable'
 
 jobs:
   - job: Test_Windows_${{ parameters.name }}
@@ -9,10 +9,6 @@ jobs:
     pool:
       vmImage: windows-latest
     steps:
-      - template: check-perl-parameter.yml
-        parameters:
-          perl: ${{ parameters.perl }}
-      - template: install-helper-tools.yml
       - bash: |
           set -e
           set -x
@@ -20,48 +16,71 @@ jobs:
           # https://github.com/camilohe/berrybrew.install/issues/1 is fixed.
           choco upgrade berrybrew --yes --ignore-checksum
         displayName: Install berrybrew
+      - bash: |
+          set -e
+          set -x
+          if [ -z "${{ parameters.perl }}" ] || [ "${{ parameters.perl }}" = "stable" ]; then
+              latest=""
+              for line in $( berrybrew available ); do
+                  if [[ "$line" =~ 5.+_64$ ]]; then
+                      latest="$line"
+                      break
+                  fi
+              done
+              if [ -z "$latest" ]; then
+                  echo "##vso[task.logissue type=error;]Could not determine latest version of Perl provided by berrybrew"
+                  echo "##vso[task.complete result=Failed;]"
+                  exit 0
+              fi
+              echo "##vso[task.setVariable variable=perl]${latest%'_64'}"
+              echo "##vso[task.setVariable variable=berrybrew_perl]${latest}"
+          else
+              echo "##vso[task.setVariable variable=perl]${{ parameters.perl }}"
+              echo "##vso[task.setVariable variable=berrybrew_perl]${{ parameters.perl }}_64"
+          fi
+        displayName: Find latest Perl provided by berrybrew
+      - template: check-perl-parameter.yml
+        parameters:
+          perl: $(perl)
+      - template: install-helper-tools.yml
       - task: CacheBeta@1
         displayName: Define tools-perl cache
         inputs:
-          key: '"v1" | "tools-perl" | "${{ parameters.cache_key }}" | "5.30.0" | "Windows"'
-          path: C:\berrybrew\5.30.0_64\perl
+          key: '"v1" | "tools-perl" | "${{ parameters.cache_key }}" | "$(berrybrew_perl)" | "Windows"'
+          path: C:\berrybrew\$(berrybrew_perl)\perl
       - bash: |
           set -e
           set -x
-          if [ ! -d C:\\berrybrew\\5.30.0_64 ]; then
-              berrybrew install 5.30.0_64
-          fi
-          berrybrew exec --with 5.30.0_64 perl -e 'use strict;use warnings;my $file = shift;open my $fh, $file or die $!;my $content = do { local $/; <$fh> };close $fh or die $!;my $q = chr(34); $content =~ s/(${q}custom_exec${q}\s*:\s*)${q}false${q}/$1${q}true${q}/;open $fh, q{>}, $file or die $!;print {$fh} $content or die $!;close $fh or die $!;' C:\\ProgramData\\chocolatey\\lib\\berrybrew\\tools\\data\\config.json
+          # It seems like we need to re-run this even if we already have a
+          # cached version. I'm guessing it does some sort of registry
+          # fiddling that's necessary for the clone command that comes after
+          # this to work. But this reinstall does not wipe the installed
+          # modules, so the later step to install deps is still much quicker
+          # when we get this perl from the cache.
+          berrybrew install "$BERRYBREW_PERL"
+          berrybrew exec --with "$BERRYBREW_PERL" perl -e 'use strict;use warnings;my $file = shift;open my $fh, $file or die $!;my $content = do { local $/; <$fh> };close $fh or die $!;my $q = chr(34); $content =~ s/(${q}custom_exec${q}\s*:\s*)${q}false${q}/$1${q}true${q}/;open $fh, q{>}, $file or die $!;print {$fh} $content or die $!;close $fh or die $!;' C:\\ProgramData\\chocolatey\\lib\\berrybrew\\tools\\data\\config.json
           cat C:\\ProgramData\\chocolatey\\lib\\berrybrew\\tools\\data\\config.json
-        displayName: Berrybrew install Perl 5.30.0 (for use as tools-perl)
+        displayName: Berrybrew install tools-perl
       - task: CacheBeta@1
-        displayName: Define runtime-perl base perl cache
+        displayName: Define runtime-perl base cache
         inputs:
-          key: '"v1" | "base-runtime-perl" | "${{ parameters.cache_key }}" | "${{ parameters.perl }}" | "Windows"'
-          path: C:\berrybrew\${{ parameters.perl }}_64\perl
-      # It seems like we need to re-run this even if we already have a cached
-      # version. I'm guessing it does some sort of registry fiddling that's
-      # necessary for the clone command that comes after this to work. But
-      # this reinstall does not wipe the installed modules, so the later step
-      # to install deps is still much quicker when we get this perl from the
-      # cache.
+          key: '"v1" | "base-runtime-perl" | "${{ parameters.cache_key }}" | "$(berrybrew_perl)" | "Windows"'
+          path: C:\berrybrew\$(berrybrew_perl)\perl
       - bash: |
           set -e
           set -x
-          if [ ! -d C:\\berrybrew\\${{ parameters.perl }}_64 ]; then
-              berrybrew install ${{ parameters.perl }}_64
-          fi
-        displayName: Berrybrew install Perl ${{ parameters.perl }} (for use as runtime-perl)
+          berrybrew install "$BERRYBREW_PERL"
+        displayName: Berrybrew install runtime-perl
       - task: CacheBeta@1
-        displayName: Define runtime-perl cache
+        displayName: Define runtime-perl clone cache
         inputs:
-          key: '"v1" | "runtime-perl-clone" | "${{ parameters.cache_key }}" | "${{ parameters.perl }}" | "Windows"'
+          key: '"v1" | "runtime-perl-clone" | "${{ parameters.cache_key }}" | "$(perl)" | "Windows"'
           path: C:\berrybrew\runtime-perl\perl
       - bash: |
           set -e
           set -x
-          berrybrew clone ${{ parameters.perl }}_64 runtime-perl
-        displayName: Berrybrew clone Perl ${{ parameters.perl }} as runtime-perl
+          berrybrew clone "$BERRYBREW_PERL" runtime-perl
+        displayName: Berrybrew clone installed Perl as runtime-perl
       - bash: |
           set -e
           set -x
@@ -72,7 +91,7 @@ jobs:
       - bash: |
           set -e
           set -x
-          berrybrew exec --with 5.30.0_64 \
+          berrybrew exec --with "$BERRYBREW_PERL" \
           perl "$CI_WORKSPACE_DIRECTORY\\bin\\cpm" install \
           --global \
           --show-build-log-on-failure \
@@ -93,37 +112,37 @@ jobs:
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 show-env.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" show-env.pl
         displayName: Show environment
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 pre-test.pl --runtime-perl ${{ parameters.perl }}
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" pre-test.pl --runtime-perl $(perl)
         displayName: Pre test
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 build-cpanfile.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" build-cpanfile.pl
         displayName: Create cpanfile for test & runtime dependencies
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 install-prereqs.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" install-prereqs.pl
         displayName: Install test & runtime dependencies
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 prep-for-tests.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" prep-for-tests.pl
         displayName: Prep distro for tests (make or ./Build)
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 install-dynamic-prereqs.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" install-dynamic-prereqs.pl
         displayName: Install dynamic dependencies added by running Makefile.PL or  Build.PL
       - bash: |
           set -e
           set -x
-          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" 5.30.0_64 run-tests.pl
+          "$CI_WORKSPACE_DIRECTORY\\ci-perl-helpers-tools\\bin\\with-perl" "$BERRYBREW_PERL" run-tests.pl
         displayName: Run tests
       - task: PublishTestResults@2
         displayName: Publish test results
@@ -131,4 +150,4 @@ jobs:
           testResultsFormat: JUnit
           testResultsFiles: $(CI_WORKSPACE_DIRECTORY)\\junit\\**\\*.xml
           mergeTestResults: true
-          testRunTitle: Windows - ${{ parameters.perl }}
+          testRunTitle: Windows - $(perl)
